name: CI/CD FlakyDoctor
description: GitHub Action for FlakyDoctor
author: Quint van Oorschot

inputs:
  openai_api_key:
    description: "OpenAI key (optional if set in env)"
    required: false

runs:
  using: composite
  steps:

    - name: Export API key
      shell: bash
      run: |
        if [ -n "${{ inputs.openai_api_key }}" ]; then
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> "$GITHUB_ENV"
        fi

    - name: Locate action directory
      id: locate
      shell: bash
      run: |
        ROOT="/__w/_actions/quintoorschot/CICD-FlakyDoctor/main"
        if [ ! -d "$ROOT" ]; then
          ROOT="${GITHUB_ACTION_PATH:-$PWD}"
        fi
        echo "Using action dir: $ROOT"
        echo "root=$ROOT" >> "$GITHUB_OUTPUT"

    - name: Generate tests.csv for FlakyDoctor
      shell: bash
      env:
        SRC_PATH: src/test/java
      run: |
        set -euo pipefail

        ROOT="${{ steps.locate.outputs.root }}"
        ACTION_DIR="$ROOT"
        export ACTION_DIR SRC_PATH

        echo "Generating tests.csv in $ACTION_DIR"

        python3 "$GITHUB_WORKSPACE/.github/workflow-scripts/generate_tests_csv.py"

    - name: Make workspace alias for script
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        WS="$GITHUB_WORKSPACE"
        TARGET="$WS/CICD-FlakyDoctor"

        echo "Workspace: $WS"
        echo "Action root: $ROOT"
        echo "Target alias: $TARGET"

        rm -rf "$TARGET"
        mkdir -p "$(dirname "$TARGET")"
        ln -s "$ROOT" "$TARGET"
        ls -la "$TARGET/FlakyDoctor/src" || true

    - name: Generate tests.csv for FlakyDoctor
      shell: bash
      env:
        SRC_PATH: src/test/java
      run: |
        set -euo pipefail
        ROOT="${{ steps.locate.outputs.root }}"

        echo "Generating tests.csv in $ROOT"
        ACTION_DIR="$ROOT"
        export ACTION_DIR SRC_PATH

        python3 "$GITHUB_WORKSPACE/.github/workflow-scripts/generate_tests_csv.py"

    - name: Run CICD FlakyDoctor
      shell: bash
      run: |
        set -e
        ROOT="${{ steps.locate.outputs.root }}"
        SCRIPT="$ROOT/CICD-FlakyDoctor.py"

        if [ ! -f "$SCRIPT" ]; then
          echo "ERROR: $SCRIPT not found in $ROOT"
          ls -la "$ROOT"
          exit 1
        fi

        echo "Running: python3 \"$SCRIPT\""
        python3 "$SCRIPT"
